### ISSUE TITLE
Trabajo Práctico 3 - Diseño de Bases de Datos

### ISSUE THREAD

**Issue by LeandroZenere** [LeandroZenere/TP3#1]
US1. Crear cursos de oficio
COMO propietario/administrador de la página web
QUIERO mostrar la oferta académica
PARA ofrecer mis cursos disponibles

Detalle o Conversación
Datos asociados:
-Fecha de comienzo.
-Título.
-Descripción.
-Objetivos
-Programa completo.
-Costo.
-Duración (en meses).
-Foto o imágen.
-Estado del mismo (disponible/no disponible).
-Categoría (Inicial, Intermedio, Avanzado).

Criterios de aceptación:
Todos los campos son requeridos.
La fecha de comienzo debe ser con el formato dd/mm/yyyy
El costo debe ser numérico.
La descripción debe contener menos de 300 caracteres.
La imagen debe tener formato jpg/png.
Los cursos deben estar visibles si su estado es disponible, de lo contrario no se podrá ver y dirá no disponible.
Todos los datos tienen que ser visibles para el usuario.
Los cursos deben estar categorizados por nivel (Inicial, Intermedio, Avanzado).

**Comment by LeandroZenere** [comment]
US2. Registrar usuarios
COMO usuario
QUIERO registrarme
PARA vender o tener acceso a los cursos.

Detalle o Conversación
Datos asociados:
-Nombre.
-Apellido.
-DNI.
-Fecha de nacimiento.
-Dirección.
-Localidad.
-Código postal.
-Provincia.
-Teléfono celular.
-Email.
-Clave de acceso.
-Rol de usuario(Administrador, docente, usuario final).

Criterios de Aceptación
Todos los campos son requeridos.
El nombre y apellido deben contener caracteres alfabéticos.
El DNI debe ser numérico y único para cada usuario (sin puntos).
El DNI debe ser verdadero.
El código postal debe ser numérico y estar registrado en datos.gob.ar.
La fecha de nacimiento debe tener 3 campos, el primer y segundo campo son 2 dígitos separados por una /, y el tercer campo debe contener 4 números separados anteriormente por una /, (sin puntos). Formato a seguir: (DIA/MES/AÑO).
La fecha de nacimiento tiene que coincidir con el nombre y apellido y estar registrado en la base de datos del Registro Civil.
El email debe tener formato correcto y ser único para cada usuario.
El email debe ser válido y estar en funcionamiento.
El número de teléfono tiene que empezar con un '+', y contener entre 6 y 14 dígitos.
Validar que el número de teléfono sea verdadero.
La contraseña debe tener mínimo 8 caracteres y máximo 16, incluyendo mayúsculas, minúsculas y un carácter especial (!@#$%&/.). No debe contener espacios.
El usuario tiene que ser activado a través de la confirmación recibida por correo electrónico.
Los usuarios públicos registrados pueden inscribirse en uno o más cursos.
Se debe proveer al usuario la posibilidad de agregar 2 roles más como: Administrador o Docente.
Cada usuario debe tener un estado (Activo/Inactivo).

**Comment by LeandroZenere** [comment]
US3. Crear las clases del curso
COMO administrador
QUIERO crear una clase dentro del curso
PARA que puedan visualizarse en la web

Detalle o Conversación
Datos asociados:
-Fecha.
-Título.
-Contenido.
-URLDrive.

Criterios de Aceptación
Todos los campos son requeridos.
La fecha de nacimiento debe tener 3 campos, el primer y segundo campo son 2 dígitos separados por una /, y el tercer campo debe contener 4 números separados anteriormente por una /, (sin puntos). Formato a seguir: (DIA/MES/AÑO). 
El URLDrive debe ser válido y estar en funcionamiento.
El administrador debe estar registrado para crear una clase dentro del curso.
El docente debe estar registrado para dictar la clase.
El usuario debe estar registrado para acceder a la clase.
Cada clase debe ser dictada por un docente y cada uno de ellos puede participar en el dictado de varias clases y cursos.

**Comment by Lautaroaavaro** [comment]
US4. Inscribirse a curso.
COMO docente
QUIERO inscribirme para brindar un curso.
PARA enseñar y que pueda ser comprado por los usuarios.

Detalle o Conversación
Datos asociados
Información del docente: apellido, nombre, celular, email, TITULO que valide conocimientos (?

Criterios de Aceptación
Todos los campos son requeridos.
El DNI debe ser numérico y no debe llevar puntos.
Los docentes deben poder subir varios cursos.

**Comment by LeandroZenere** [comment]
US5. Registrar usuarios
COMO usuario
QUIERO registrarme
PARA visualizar los cursos.

Detalle o Conversación
Datos asociados
Nombre.
Apellido.
DNI.
Fecha de nacimiento.
Dirección.
Localidad.
Código postal.
Provincia.
Teléfono celular.
Email.
Clave de acceso.

Criterios de Aceptación
Todos los campos son requeridos.
El DNI debe ser numérico (sin puntos), único y real para cada usuario.
El email debe tener formato correcto y ser único para cada usuario.
El email debe ser verificado a través de un correo automático.
Los usuarios pueden inscribirse en uno o más cursos.
La contraseña debe tener mínimo 6 caracteres, incluyendo mayúsculas, minúsculas y un carácter especial.

**Comment by LeandroZenere** [comment]
US4. Agregar cursos al carrito de compras
COMO Usuario final registrado y validado
QUIERO agregar cursos al carrito de compras.
PARA poder adquirir un curso

Detalle o Conversación
Datos asociados:
Cursos seleccionados en la web con: foto, título del curso, duración, costo y monto total.

Criterios de Aceptación
Todos los campos son requeridos.
Se debe validar que el usuario tenga su cuenta en Activo.
Se debe validar que el curso este disponible en el sitio web.
El usuario podrá comprar uno o más cursos.
El usuario podrá eliminar fácilmente uno o varios cursos desde el carrito.
Los cursos en el carrito deben mostrarse con su información relevante.
Los cursos deben permanecer en el carrito hasta que se eliminen o se complete la compra.
Mostrar el costo unitario y total de los cursos en el carrito antes de confirmar la compra.

**Comment by LeandroZenere** [comment]
US5. Seleccionar Medio de Pago.
COMO usuario final registrado
QUIERO poder seleccionar un medio de pago
PARA realizar el pago del curso e insicribirme.

Detalle o Conversación
Datos asociados:
-Opciones de medios de pago: Tarjeta de crédito/débito, transferencia bancaria.
-Detalles básicos de tarjetas: Numero de tarjeta, fecha de vencimiento, código de seguridad, nombre que figura en la tarjeta y documento del titular.

Criterios de Aceptación:
Todos los campos son requeridos.
Los usuarios deben poder elegir un medio de pago entre las opciones disponibles.
El agente de cobro debe validar los datos de la tarjeta, que sean únicos y reales y que disponga del monto necesario para realizar la compra. 
Mostrar un botón para confirmar el medio de pago.
Al confirmar el medio de pago mostrar un resumen de la compra.
Una vez confirmada la compra por el agente de cobro, se registra la fecha de compra, el nombre de usuario que realizó la compra y el monto total. Estos datos se enviarán al correo vinculado del usuario registrado.
Mostrar un mensaje de confirmación para aprobar la compra por parte del usuario.
Se le otorga acceso al usuario al curso automáticamente después de confirmarse la compra.

**Comment by LeandroZenere** [comment]
US9. Gestión de cursos para los docentes
COMO docente inscripto en un curso
QUIERO poder agregar, editar y eliminar contenido del curso
PARA proporcionar materiales de estudio y recursos a los usuarios.

Detalle o Conversación
Datos asociados

Acceso con el correo y la contraseña registrada del docente.
Acceso a lista de usuarios inscriptos.
**FALTA 
FALTA
FALTA**

Criterios de Aceptación
Los docentes deben poder cargar materiales, como presentaciones y documentos, para cada clase.
Los docentes pueden editar o eliminar contenido existente según sea necesario.
El contenido debe estar disponible para los estudiantes inscritos en la clase correspondiente. Se usará también acceso restringido dependiendo el rol (Administrador, Docente). **CAMBIAR/REVISAR ESTO ÚLTIMO**

**Comment by geromontiel200** [comment]
US.6 Confirmar la compra del curso
COMO usuario final
QUIERO confirmar la compra
PARA iniciar las clases o cursos

Datos asociados:
-Fecha de compra.
-Los cursos que han sido seleccionados.
-Usuario que compra el curso
-Monto total
-Método de pago seleccionado

CRITERIOS DE ACEPTACION:
Mostrar un resumen de la compra con todos los datos asociados a la misma.
Dar 2 opciones al usuario para que pueda confirmar o cancelar la compra.
Mostrar un mensaje de confirmación o cancelación dependiendo la opción que eligió el usuario.
Mostrar un mensaje de éxito o cancelación de la compra.
Una vez confirmada la compra por el agente de cobro, se registra la fecha de compra, el nombre de usuario que realizó la compra y el monto total. Estos datos se enviarán al correo vinculado del usuario registrado.
Se le otorga acceso al usuario al curso automáticamente después de confirmarse la compra.
